apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: matomi-issuer
  namespace: matomi
spec:
  acme:
    email: ezekielmatomi588@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: matomi-letsencrypt-private-key
    solvers:
    - http01:
        ingress:
          class: nginx