apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-depl
  template:
    metadata:
      name: mongo
      labels:
        app: mongo-depl
    spec:
      containers:
      - name: mongo-img
        image: mongo
        ports:
        - containerPort: 27017



---

apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
spec:
  selector:
      app: mongo-depl
  ports:
  - port: 27017
    targetPort: 27017
    


  
  
  