apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-eml-deployment
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      name: apache2-eml-app
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd
        ports: 
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: apache-eml-service
spec:
  type: ClusterIP
  selector: 
    app: apache2
  ports:
  - name: apacheport
    port: 80
    targetPort: 80


