apiVersion: v1
kind: Service
metadata:
  name: matomiservice
spec:
  selector:
      application: app
  type: NodePort
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
      nodePort: 30000

  