apiVersion: v1
kind: Pod
metadata: 
  name: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapplaith
    image: laithharb/web-app:v2
    ports:
    - containerPort: 3000
