apiVersion: v1
kind: Service
metadata: 
  name: webapp-service
spec:
  type: NodePort
  ports:
  - name: webapp-service
    port: 3000
    targetPort: 3000
    nodePort: 30050
  selector:
    app: webapp
